### ISSUE TITLE
Split annotation doesn't list genes found in deletions

### ISSUE THREAD

**Issue by zhouyangyu** [lgmgeo/AnnotSV#1]
Hello,

I am using AnnotSV in our workflow and I am impressed by its comprehensiveness. However, we found an issue regarding the annotation of genes found in deletions.

Each SV is first annotated as a whole (the "full" annotation type), with a column listing the affected genes that spans the two breakpoints. This method makes sense for duplication, inversion and translocation, but not for deletions because a deletion affects all the genes that it spans in addition to genes spanning its two breakpoints. For example, annotation of a DEL chr9:21850000-22100000 should list CDKN2A in addition to MTAP and CDKN2B-AS1 (two genes spanning the breakpoints), and all three genes should be annotated in "split". Therefore, it would be helpful if you could add this functionality to the pipeline.

Thank you so much for developing this very useful tool!

Best,
Joe

**Comment by zhouyangyu** [comment]
I ran the 2.1 version on the same input, and the "full" annotation listed all the genes that a deletion spans. I believe this is caused by some changeS to the code since 2.1.

**Comment by lgmgeo** [comment]
Hi Joe,

Really sorry for the delay in my answer.

Actually, all genes overlapped by the SV (even with 1 bp) are reported.
But if the input ALT format consists in a complex rearrangement with breakends ( e.g. N[5:12436813[ ), AnnotSV 2.2 annotates only one breakend, because it can not define if this SV is a translocation or a deletion or... 

Indeed, if the chromosome from the CHROM column and the chromosome from the ALT column are the same, AnnotSV can not set the type of the SV itself (del or tra or dup... are all possible).

Best,

Véronique

**Comment by lgmgeo** [comment]
please look at AnnotSV version 3.3.1:
 the comprehension of the square-bracketed notations relies now on the [homogenization rules](https://github.com/EUCANCan/variant-extractor#homogenization-rules) from the [variant-extractor](https://github.com/EUCANCan/variant-extractor) tool (provided by Rodrigo Martin).

cf https://github.com/lgmgeo/AnnotSV/issues/77
