### ISSUE TITLE
empty of AnnotSV_ranking_score column

### ISSUE THREAD

**Issue by charliechen912ilovbash** [lgmgeo/AnnotSV#115]
In my output, the `AnnotSV_ranking_score` column is empty, is there any possible reason?

**Comment by lgmgeo** [comment]
Hi @charliechen912ilovbash,

For the ranking, AnnotSV needs to have the SV type feature in the input file.
Do you use a BED or a VCF input file ?

 In order to be able to classify the SV:
- With a BED, please use the `svtBEDcol` option:

```
-svtBEDcol: Number of the column describing the SV type (DEL, DUP) if the input SV file is a BED
```

- With a VCF file, the "SVTYPE" values should be one of DEL, INS, DUP, INV, CNV, BND, LINE1,
SVA, ALU. In addition, the <CN0>, <CN2>, <CN3>... angle-bracketed ID from the "ALT" column should be used in
case of SVTYPE=CNV in the INFO column.

Best regards,

Véronique

**Comment by charliechen912ilovbash** [comment]
Yes I am using the svtBEDcol column, and in the column there are only DEL, BND, INS, INV, DUP.
Is the forth column counted as 4 or 3 ?
0,1,2,3  > -svtBEDcol 3
1,2,3,4  > -svtBEDcol 4

**Comment by lgmgeo** [comment]
So you give a bedfile in input, ok.
Please use -svtBEDcol 4.
The ranking is available for DEL and DUP only (ACMG/Clingen rules).

**Comment by charliechen912ilovbash** [comment]
I got the Annot score, did not notice that only in 'full' mode can get this score.
Is it possible to calculate this score for each gene so even in the 'split' mode can also obtain this score?
Or, do the gnomAD pLi and exAc pLi have some moderate cutoff for gene filtering? Currently only 0.9 for extremely pathogenic, maybe there could be some like AnnotSv score from level 1 to 5, to include the middle level SV-mutated gene.

**Comment by lgmgeo** [comment]
The SV ranking score is based on the consensus recommendations of ACMG and ClinGen (published in 2020).
No way to calculate an equivalent score for each gene, because this calculation depends on the SV breakpoints, the SV length... (and so on). 

FYI, AnnotSV allows a phenotype-driven SV analysis. 
- In this aim, the user can provide the phenotype of the patient as a list of HPO terms. This is optionnal but it’s highly recommended to use it for better prioritization. This means that the user can identify relevant SV, based on how similar the phenotype of the patient is to the gene overlapped with this SV. 
- Each overlapped gene is scored depending on the patient phenotype. Basically, the more the gene matches the patient's phenotype, the higher the score is. This score is between 0 and 1 and becomes very specific when it is greater than 0.7.

Hope this can help...
Best,
Véronique
