### ISSUE TITLE
How to update miRTargetLink data

### ISSUE THREAD

**Issue by wx904** [lgmgeo/AnnotSV#123]
Hi,

I'm totally new to AnnotSV. In the README.AnnotSV_latest.pdf file, you mentioned “Validated_miRNA-gene_pairs_hsa_miRBase_<version>_GRCh38_location_augmented.tsv” file. Should I contact the author to request this file or download directly from their web?

Best,
Xiao

**Comment by lgmgeo** [comment]
Hi Xiao,

The version of miRTargetLink data embedded in AnnotSV v3.1 (November, 2021) is 2020-12-11 (v2.0, data provided by the authors). 
- You can find the formatted data in the AnnotSV install: `$ANNOTSV/share/AnnotSV/Annotations_Human/FtIncludedInSV/RegulatoryElements/GRCh38/miRTargetLink_*_GRCh38.sorted.bed`
- Corresponding annotations will be in the `RE_gene` output column.

No new miRTargetLink  version since: https://ccb-compute.cs.uni-saarland.de/mirtargetlink2

If you wish to contact the authors, you can email [Fabian Kern](https://www.ccb.uni-saarland.de/people/fabian-kern/
).

Best,
Véronique

**Comment by wx904** [comment]
Hi Véronique,

Thank you for your reply and I'm so glad to know about this.

thanks,
Xiao
