### ISSUE TITLE
misleading OMIM annotation

### ISSUE THREAD

**Issue by JMdeSteAgathe** [lgmgeo/AnnotSV#156]
Hi,
I have an error concerning the omim annotation
when running `chr4:147676861-147684226 DEL` (hg38), 
I get this OMIM_ID annotation:

> [607871](https://www.omim.org/entry/607871) OMIM_morbid : yes

which unfortunately concerns another gene, in another chromosome `FBXO11`, having one of its previous symbol misleading the matching "prmt9"
my recommendation would be to use the ensembl ID `ENSG00000164169` as matching key in the `genemap2.txt` file from OMIM.
thank you for making annotSV :)
Jean-Madeleine

**Comment by lgmgeo** [comment]
Hi,

Indeed, unfortunately, [ FBXO11 has PRMT9 as previous symbol](https://www.omim.org/entry/607871) :o(
![image](https://user-images.githubusercontent.com/49909073/217777472-7ab65259-fb73-4a21-9138-12abda7551ca.png)
This is why AnnotSV reports this OMIM.

For the future annotations version, I think about adding a check during the parsing of the `genemap2.txt` file from OMIM.
Before to associate `Alternative titles` and `symbols` to an OMIM ID, I will check their genomic coordinates with those of the `Approved Gene Symbol`.

Thank you for the feedback.

Véronique

**Comment by JMdeSteAgathe** [comment]
Thanks Véronique! great

**Comment by XVanhoye** [comment]
Hi, 
I have similar observations : 
`21:5098671-6120931 DEL` : when annotate with RefSeq, it attributes genes _SIK1_ and _SIK1B_ (and OMIM ID associated), which are not in the CNV ; maybe because of aliases of LOC102724428 in the CNV ([https://www.ncbi.nlm.nih.gov/gene/102724428]()) ? Running the analysis with Ensembl transcript fix this
`7:29194672-29496306 DUP` : it attribute the OMIM ID 159400, related to gene _MPZ_, not included in the CNV. Is it because _CHN2_ (a gene included in the CNV), also correspond to a phenotype description of MPZ ? (https://www.omim.org/entry/618184?search=CHN2&highlight=chn2) 

Thanks a lot !

**Comment by lgmgeo** [comment]
Hi, 

I have added a fix for misleading OMIM annotation in the dev branch.
This will be distributed soon with the next annotation release.

1 - `chr4:147676861-147684226 DEL`
=> Ok, no more bad OMIM_ID annotation (607871 no longer reported)

2 - `21:5098671-6120931 DEL`
SIK1 is a special case. 
Look at the UCSC genomic coordinates for SIK1(https://genome.ucsc.edu/cgi-bin/hgSearch?search=NM_173354&hgsid=1879097202_ekQRZ78BhVG8APrtI1hPXrkg83Q2&db=hg38) :
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/25b484c1-29fd-4363-99cc-48cb4ef5f7db)
Your CNV overlaps SIK1 according to NM_173354 in UCSC.
=> SIK1 is reported in a split line, the associated OMIM too.
With ENSEMBL, indeed, no problem:
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/3e9cb316-8ba4-45fa-9766-3b9889fe9b22)
=> SIK1 is not reported in a split line

3 - `7:29194672-29496306 DUP` 
=> Ok, no more bad OMIM_ID annotation (159440 no longer reported)

I will notify you here as soon as the updated annotations are published

Véronique

**Comment by lgmgeo** [comment]
AnnotSV 3.4 is posted.
Let me know if everything works well on your side.
