### ISSUE TITLE
Gnomad variant effect columns

### ISSUE THREAD

**Issue by idraktt** [lgmgeo/AnnotSV#192]
I just wanted to check description of these columns. Is these columns same as gene classification introduced by the Gnomad and used in their paper? I didn’t find information about them in readme or maybe I missing something.

AnnotSV command:
AnnotSV -SVInputFile QGP_SV_ins_fixed.bed -bedtools /gpfs/software/genomics/bedtools/2.26/bin/bedtools -SVInputInfo 1 -svtBEDcol 4 -samplesidBEDcol 6 -genomeBuild GRCh37

I am using BED file as a input: 
![image](https://github.com/lgmgeo/AnnotSV/assets/2089111/abd80b0c-f703-4cce-8d08-f99310c03dc8)

Columns that i didnt find in readme:
![image](https://github.com/lgmgeo/AnnotSV/assets/2089111/ff076aec-fb01-4e19-a756-0a26403765a6)

**Comment by lgmgeo** [comment]
Hi @idraktt,

Actually, these annotation columns are not distributed with AnnotSV.
That's why they are not in the README.

Let's have a look at your install.
Can you run these commands:
```
ls -l $ANNOTSV/share/AnnotSV/Annotations_Human/Users/*
ls -l $ANNOTSV/share/AnnotSV/Annotations_Human/Users/*/*
```

Else, do you have any annotation file indicated in your configfile that I can't see in your command line?
The "configfile" can be located:
- in the same directory as your input file
- in the installation directory in $ANNOTSV/etc/AnnotSV/configfile

**Comment by idraktt** [comment]
Dear @lgmgeo ,

Thank you very much for your quick response. 

Someone else added Gnomad Annotations on our HPC cluster to AnnotSV installation. Now it is clear from where they are coming. 
![image](https://github.com/lgmgeo/AnnotSV/assets/2089111/f0e37638-6004-4850-896b-7542308fd403)

**Comment by lgmgeo** [comment]
Great!
