### ISSUE TITLE
[Improvement] Read HPO from phenopacket file

### ISSUE THREAD

**Issue by looxon93** [lgmgeo/AnnotSV#193]
Hi, 

Thanks for a great tool, it is very useful. 
I was wondering if HPO terms can be provided in a phenopacket schema file instead of a list of terms? That is simplifying things if you have larger number of terms you want to include and it doesn't enlarge command line. 

Best,
Luka

**Comment by lgmgeo** [comment]
Hi Luka,

Actually, no. AnnotSV can only use a list of HPO terms in input. 
But you can use the configfile to set the `-hpo` option instead of the command line.

cf [README](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf):
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/e1894394-8745-4216-adac-192b2a39f44c)

Just to let you know, a large number of HPO terms to describe  a human phenotype will be time consuming. 
The HPO terms need to be as specific as possible.

Best,
Véronique
