### ISSUE TITLE
No vcf or circos results from the web server

### ISSUE THREAD

**Issue by DeMagicscience** [lgmgeo/AnnotSV#213]
Thank you for developing AnnotSV, which is a very powerful and popular tool.

When I am using the web server, I encounter a problem: I cannot obtain the circos plot. The following message appeared in the "RetrieveJob" page,

"No VCF for the job with id "xxxxxxxxxx"."

When I run job on the web server, I only upload the SV input file, which is a vcf file generated from Delly.  Other parameters are default. I can get the "AnnotSV tsv", "knot html" and "knot xlsm" results.

I will be very grateful if you can tell me how can I get the circos plot.

Thank you for your time!

**Comment by lgmgeo** [comment]
Hi @DeMagicscience ,

Actually, you first need the VCF output file created by variantconvert to then get the circos plot.
It seems that the problem is with the creation of the VCF output file.

In your VCF input file, do you have any SVs absent from all samples? 
Something like:
```
chr10   15333000     .    T    <INV>   300     PASS    SVTYPE=INV;END=15335000  GT   0/0     0/0
```
If so, this is a know bug with variantconvert (https://github.com/lgmgeo/AnnotSV/issues/180). 

The solution is therefore to remove these SV from your VCF input file.

Please, let me know if this solve the problem.

Best,

Véronique

**Comment by DeMagicscience** [comment]
Hi, @lgmgeo Thank you for your prompt reply.
Yes. it works! 
I have another question. I want to make a circos plot to display the SV using other R packages (for example, RCircos). From which file, can I get the necessary information?
for example, I want to draw a link plot to display the translocations, the necessary information are:
(1) Chromosome: 
(2) chromStart
(3) chromEnd
(4) Chromosome.1
(5)  chromStart.1
(6) chromEnd.1
I have read the results of  .tsv and .vcf file from annotSV, but cannot find such information.

**Comment by lgmgeo** [comment]
To extract the SV input fields and insert the data in the TSV outputfile, you need to set `-SVinputInfo` to 1 in the AnnotSV command line.
