### ISSUE TITLE
v3.4 Exomiser issue

### ISSUE THREAD

**Issue by abrusell** [lgmgeo/AnnotSV#216]
Hi Véronique,
Thanks for the great work.
I've installed v3.4, and I'm having issues with exomiser and phenogenius.
Specifying the GRCh38 build in the configfile (-genomeBuild:  GRCh38) and in the command line, I get the following error in the log exomiser.tmp file: 

```
2024-02-29 16:37:19.192  INFO 2155 --- [           main] com.zaxxer.hikari.HikariDataSource       : exomiser-genome-hg19-2309 - Starting...
2024-02-29 16:37:20.195 ERROR 2155 --- [           main] com.zaxxer.hikari.pool.HikariPool        : exomiser-genome-hg19-2309 - Exception during pool initialization.

org.h2.jdbc.JdbcSQLException: Database "/g100_work/OPBG2_prod2023/NGS_tools/ExomiserData/data/2309_hg19/2309_hg19_genome" not found [90013-197]

```
I've tried to change  "exomiser.hg19.data-version=2309" to "exomiser.hg38.data-version=2309" in the configfile
and now it doesn't complain anymore but the column "Exomiser_gene_pheno_score" in the output file reports only "0" or "-1" values

Furthermore, I've correctly installed PhenoGenius in the $AnnotSV_3.4/share/python3/phenogenius directory, but I get this error:

```
...running PhenoGenius for 4524 gene names (March 01 2024 - 15:37)

child process exited abnormally
```

Any hints on how to solve these errors?

Thanks

**Comment by lgmgeo** [comment]
I am out of the office. I will be back on March 11 and will respond to your issue at that time.

**Comment by lgmgeo** [comment]
Ok, 2 problems here:
- Exomiser
- PhenoGenius

Let's begin with the first one: **Exomiser**.

First of all, it should be noted that the Exomiser analyzes are independent of the genome build (cf https://github.com/lgmgeo/AnnotSV/issues/12).
The Exomiser module only uses the name of the genes (and not the position of the genes).
=> So don't worry about seeing "hg19" in the output.

The prolem is:
```
org.h2.jdbc.JdbcSQLException: Database "/g100_work/OPBG2_prod2023/NGS_tools/ExomiserData/data/2309_hg19/2309_hg19_genome" not found [90013-197]
```

Can you give me your exact AnnotSV command line?
Did you use the `-annotationsDir` option?
Did you run AnnotSV using Bioconda?

Because in a standard install, the exomiser database is located in:
$ANNOTSV/share/AnnotSV/Annotations_Exomiser/2309/2309_hg19/2309_hg19_genome.h2.db

As an example, the `-annotationsDir` option can be set to `$ANNOTSV/share/AnnotSV`.
WARNING: the directory architecture must remain the same as in AnnotSV:
```
ls $ANNOTSV/share/AnnotSV
Annotations_Exomiser  
Annotations_Human  
jar

ls $ANNOTSV/share/AnnotSV/Annotations_Exomiser/
2309
```

**Comment by abrusell** [comment]
So I've restored the $ANNOTSV/share/AnnotSV/Annotations_Exomiser/2309/2309_hg19/2309_hg19_genome.h2.db file and everything works!

Thank you!

**Comment by poddarharsh15** [comment]
Hi @lgmgeo,

Apologies for bringing this up here, but I believe it will be easier to clarify. I plan to use the 2402_hg38/ dataset for Exomiser instead of 2402_hg19/, as all of my VCF files are aligned to GRCh38. Would it be sufficient to simply change exomiser.hg19.data-version=2402 to exomiser.hg38.data-version=2402 in the applications.config file? Will this allow Exomiser to process the GRCh38 data correctly?

Thank you for your guidance.

**Comment by lgmgeo** [comment]
The Exomiser analyzes are independent of the genome build (cf https://github.com/lgmgeo/AnnotSV/issues/12).
The Exomiser module only uses the name of the genes (and not the position of the genes).
The 2402_hg19 file is OK for hg38 analysis, but it is to notice that the latest version of Exomiser officially supported by AnnotSV is 2309. I have never tested Exomiser version 2406.

**Comment by julesjacobsen** [comment]
@lgmgeo - have you tried updating your version of the exomiser-rest-prioritiser to [exomiser-rest-prioritiser-14.1.0.jar](https://github.com/exomiser/Exomiser/releases/download/14.1.0/exomiser-rest-prioritiser-14.1.0.jar)? This doesn't need the spurious `exomiser.hg19.data-version=2309` in the `application.properties` and it only requires the [2410_phenotype](https://g-879a9f.f5dc97.75bc.dn.glob.us/data/2410_phenotype.zip) data to run.

**Comment by lgmgeo** [comment]
Hi @julesjacobsen, thanks for this information.
I haven't reviewed this version, I'll keep that in mind for a near future.

**Comment by lgmgeo** [comment]
Hi Jules,

I try updating the AnnotSV version of the exomiser-rest-prioritiser to exomiser-rest-prioritiser-14.1.0.jar.

Here is my `application.properties` file:
```
spring.application.name=exomiser-prioritiser-service

server.servlet.context-path=/exomiser/api/prioritise
server.port=10000
server.servlet.application-display-name=Exomiser Prioritiser Server

#Absolute system path where the exomiser data is installed
exomiser.data-directory=/PROGS/EXTERN/AnnotSV/AnnotSV_latest/share/AnnotSV/Annotations_Exomiser/2309
exomiser.phenotype.data-version=2309
exomiser.phenotype.random-walk-preload=true

#Actuator configuration
info.name=${server.display-name}
info.build.version=${project.version}
info.build.timestamp=${build.timestamp}
``` 
I have:
![Image](https://github.com/user-attachments/assets/864682b5-a438-45c8-bf30-ec459332e4ce)

When I run:
```
java -Xmx4g -jar exomiser-rest-prioritiser to exomiser-rest-prioritiser-14.1.0.jar --server.port=10000 --spring.config.location=application.properties  &
```
I have this error:
![Image](https://github.com/user-attachments/assets/afac67f9-7f79-4e63-bb79-0784ddbce5c2)

Why does Exomiser is looking for: /PROGS/EXTERN/AnnotSV/AnnotSV_3.4.4/share/AnnotSV/Annotations_Exomiser/2309/2309_phenotype/2309_phenotype?

Thanks for your help!

PS: I will update the `exomiser.phenotype.data-version` in a second time.

**Comment by lgmgeo** [comment]
@julesjacobsen 
Tested and validated.
This will be present in the next update of the annotations
