### ISSUE TITLE
Possible to increase number of overlapping features returned?

### ISSUE THREAD

**Issue by mmlian05** [lgmgeo/AnnotSV#231]
Thank you Véronique and your team for coming up with AnnotSV. The tool is very useful for my CNV annotation exploration. 
 
Am wondering if there is a maximum number of features returned for a matching SV (query)? This is because in my CNV list, I have a very large CNV (~2Mb). The number of overlapping features (at 100% overlap) returned stops at 50, after which “…” is appended. Not sure if the number of overlapping features can be increased?
 
Thank you so much for your time in answering my queries.

**Comment by lgmgeo** [comment]
Hi @mmlian05,

Thank you for your kind words :o) 

Very large SV can sometime overlap too many features locations. It appears that depending on the visualisation program used (spreadsheet programs mostly) this annotation can be truncated. In order to avoid such embarrassing glitch and maybe also because overlapping so many features is already a problem, AnnotSV restricts the number of overlapping reported features.
Here are the features in question:
- RE_gene
- po_B_gain_someG_source
- po_B_gain_someG_coord
- po_B_loss_someG_source
- po_B_loss_someG_coord

If you want to change this behavior, you have to hack the code in 2 files:
(replace 19 or 49 by the desired maximum)

$ANNOTSV/share/tcl/AnnotSV/AnnotSV-benignsv.tcl:
```
lappend L_poBenignText($SVtoAnn) "[join [lrange $L_benign_source($SVtoAnn,$svtype,allG) 0 19] ";"]..."
lappend L_poBenignText($SVtoAnn) "[join [lrange $L_benign_coord($SVtoAnn,$svtype,allG) 0 19] ";"]..."
lappend L_poBenignText($SVtoAnn) "[join [lrange $L_benign_source($SVtoAnn,$svtype,someG) 0 19] ";"]..."
lappend L_poBenignText($SVtoAnn) "[join [lrange $L_benign_coord($SVtoAnn,$svtype,someG) 0 19] ";"]..."
```
$ANNOTSV/share/tcl/AnnotSV/AnnotSV-regulatoryelements.tcl:                 
```
set g_re($SV) "[join [lrange $g_re($SV) 0 49] ";"]..."
```
Best,
Véronique

**Comment by mmlian05** [comment]
Hi Véronique,

Thank you for the advice. Will try them out. 

Wondering for user's own annotation specifically FtIncludedInSV, and SVIncludedInFt, which *.tcl file and code line should i modify to increase number of overlapping features? 

Thank you! :)

Best regards,
Michelle

**Comment by lgmgeo** [comment]
>Wondering for user's own annotation should i look into the following *.tcl and line to modify the code?
$ANNOTSV/share/tcl/AnnotSV/AnnotSV-userBED.tcl

Absolutely, yes
