### ISSUE TITLE
Tmp file not found while sorting cnv.bed

### ISSUE THREAD

**Issue by boboppie** [lgmgeo/AnnotSV#29]
Dear developers,

Thanks for the latest release **2.5.1**. I'm testing this version with my cnv calls (in BED format). Here is my command:

`$ANNOTSV/bin/AnnotSV -SVinputFile 141.cnv.bed -snvIndelFiles 141.hard-filtered.vcf.gz -outputFile ./141.cnv.with-vcf.annotated.tsv -genomeBuild GRCh38 -svtBEDcol 6`

Then I got an error:

> sort -k1,1 -k2,2n ./141.cnv.formatted.sorted.bed.tmp >> ./141.cnv.formatted.sorted.bed
> sort: cannot read: ./141.cnv.formatted.sorted.bed.tmp: No such file or directory
> Exit with error
> 

I don't see _141.cnv.formatted.sorted.bed.tmp_ in my working directory. 

I tested it with a vcf as input file, and it works just fine.

Would you please advise what might cause the issue?

**Comment by lgmgeo** [comment]
Hi Fengyuan,

Can you check if the bug still occurs without `-snvIndelFiles 141.hard-filtered.vcf.gz`?

Anyway, It might be easier for me if I could reproduce the bug.
Can you email me your input file(s)? (Only `141.cnv.bed` if the bug is `-snvIndelFiles` independant)
(veronique.geoffroy@inserm.fr)
I'll test it and get back to you.

Best,
Véronique

**Comment by boboppie** [comment]
Dear Véronique,

Thank you for your quick reply. I've double checked the input BED file, unfortunately I made a mistake, it is not a BED file at all. Then I replaced it with the correct one and AnnotSV works like a charm. Sorry for the trouble.

Many thanks for your support and I will close this ticket.

Best wishes,
Fengyuan
