### ISSUE TITLE
Add column for frequencies in databases for B_* infos (and eventually for P_*)

### ISSUE THREAD

**Issue by kalon33** [lgmgeo/AnnotSV#40]
Would it be possible to include in annotated results frequencies from SV databases? It would help to better assess some events.

Thanks for your help and for your useful software.

**Comment by lgmgeo** [comment]
Hi Nicolas,

The idea of AnnotSV 3.0 was to stick to the new ACMG criteria (based in part on benign/pathogenic SV).

The "frequencies" from DDD, DGV, gnomAD, 1000g... are no longer reported with AnnotSV 3.0.
It's basically because the output was getting bigger and bigger (with the SV sources increase).

Actually, the frequencies has been used to create the benign/pathogenic SV data sources in AnnotSV.
For example, benign SV have been merged in AnnotSV from gnomAD, ClinVar, ClinGen, DGV, DDD, 1000g and IMH. The benign SV extraction method from each source is described in the README. As an example, putatively benign variants were selected from gnomAD i) if at least one population allele frequency > 1% OR ii) if the homozygous individuals count > 5.

So if you are interested in filtering SV from the frequencies, this is no longer possible...

If you want to use different requirements to define a benign SV, you can create/complete your own data files in:
$ANNOTSV/share/AnnotSV/Annotations_Human/SVincludedInFt/BenignSV/GRCh3*/

Hope this could help,

Best,
Véronique

**Comment by Bin-Guan** [comment]
The population frequency information  in gnomAD and 1k genome was useful for me for filtering in version 2.2. The new strategy in v3.0 makes sense, however, I'm afraid that the version 3.0.5 may have a bug in the ACMG classification for BenignSV, because it often classifies variants common in gnomAD as ACMG 4 or 5 in my experience.  For example, my input 1_108190708_108194629_DEL_1 (GRCh38) was classified as "ACMG_class 4", although gnomAD-SV_v2.1_DEL_1_6945 is actually included in the bed file ($ANNOTSV/share/AnnotSV/Annotations_Human/SVincludedInFt/BenignSV/GRCh38/benign_Loss_SV_GRCh38.sorted.bed): 1       108190702       108194629       gnomAD-SV_v2.1_DEL_1_6945. This deletion has an AF of 0.21 and a hmz count of 532 in gnomAD. The example variant and the gnomAD variant is only 6 bp off at the start position. What's the problem here? Thanks.

**Comment by lgmgeo** [comment]
Hi,

No bug actually in the v 3.0.5.

Here are some annotation results from your example (1_108190708_108194629_DEL_1, GRCh38):
```
ACMG_class: 4
AnnotSV_ranking_score: 0.9
AnnotSV_ranking_criteria: 
- 1A: Contains protein-coding or other known functionally important elements.
- 2C-1 (SLC25A24): Partial overlap with the 5' end of an established HI gene / morbid gene (3' end of the gene not involved) and coding sequence is involved
- 3A (1 gene): 0–24 genes wholly or partially included
- 5F: Inheritance information is unavailable or uninformative
```

In each section, only 1 criterion (from the most pathogenic to the least) is assigned.
In your example, criterion 2F (completely contained within an established benign Loss region) is not assigned because criterion 2C-1 is more pathogenic.

Indeed, the SLC25A24 gene is an OMIM morbid gene. The molecular basis of the Fontaine progeroid syndrome is known; mutations has been found in the gene (see the "Molecular Genetics" section at [https://www.omim.org/entry/608744](https://www.omim.org/entry/608744)).

Regarding your DEL, the 2C-1 criteria is verified (coding sequence of the morbid gene is involved).
This explains the ACMG_class of 4.

However, if you wish, you can filter out DEL that are completely contained within an established benign loss region with the B_loss_source annotation column (by filtering out SV where this value is not empty), although I don't recommend it.

Hope that it's clearer.

Véronique

**Comment by Bin-Guan** [comment]
Thanks for your detailed explanation, Véronique. 
In this example, can you consider applying BA1 criterion for AF in gnomAD > 5%?  So that BA1 will override the rest of Path criteria.
Thanks for pointing out filtering based on B_loss_source. This approach should work well for us. At least it's safe to filter out AD genes. Could be a little bit risky for AR genes based on 1% AF and 5 hmz cut-off, if working with a relatively common disease.

**Comment by lgmgeo** [comment]
> In this example, can you consider applying BA1 criterion for AF in gnomAD > 5%? So that BA1 will override the rest of Path criteria.

Sorry, which criterion is BA1 for you? (Please refer to the Table1 of the [Scoring_Criteria_AnnotSV_latest.xlsx](https://lbgi.fr/AnnotSV/Documentation/Scoring_Criteria_AnnotSV_latest.xlsx) file).


> Could be a little bit risky for AR genes based on 1% AF and 5 hmz cut-off, if working with a relatively common disease.

I totally agree with you. Thanks for this feedback.
It could make sense to add a new option using different benign SV sets depending on the scenario:
- rare disease (benign if >1% and 5 hmz cut-off)
- relatively common disease (benign if >5% and 5 hmz cut-off)
Can you give me your feeling?

**Comment by Bin-Guan** [comment]
Sorry about the BA1. BA1 (stand-alone benign criterion) is from the Richards 2015 ACMG guideline for SNV/indels. I did not know that the Riggs 2020 paper did not mention BA1 at all, but used 2F instead. After reading Riggs 2020 paper again, my understanding is that 2F with -1 point acts similar to BA1. The 2F is assigned with either 0 or -1, and other criterion such as 2C-1 does not affect whether to assign 2F. Only under rare instances, "expert opinion" can dictate a criterion to be dropped if there is a good reason.
The main question for 2F here is whether there is an objective method to determine whether it is in "an established benign CNV region". In this regard, we probably can use the BA1 concept in Richards paper, where >5% in general population warrants 2F = -1. The SLC25A24 example then will become a VOUS. For a variant with AF = 0.21, probably 2F should be assigned as -2. But one might need to have a big cohort to determine the best scoring system. 
Adding a new option with disease prevalence in mind likely will be helpful. This probably requires considering both AF and known inheritance pattern (AD or AR). For simplicity, 1 and 5% AF cutoffs might work well for most groups. 
Thank you for the nice tool.

**Comment by lgmgeo** [comment]
New idea:
I will add a `-benignAFcutoff` option, set by default to 1% and with a range values from 0.1% to 10% ([0.1-10[).
So that each user can defined the AF cutoff for benign SV on their own.

As the annotation sources will need to be updated for that, I will be adding that this summer (not before).

**Comment by Bin-Guan** [comment]
How to apply the Richards 2015 or Riggs 2020 guidelines are interesting, in particular, by computer. In Richards 2015, we routinely apply both benign and path criteria, and then apply Bayesian for the final classification (https://pubmed.ncbi.nlm.nih.gov/29300386/). Thus, I thought CNVcalc would use similar strategy combine evidences, but CNVcalc did not. Instead, CNVcalc allows only one criterion under section 2, the warning message 
"Enabling this checkbox will automatically disable already checked box/scored rows under this section", however,  does not imply that there is an order from more pathogenic to less pathogenic in that section. "under this section" means "within this section". 

I'm still in training for the CNV classification, I'll ask the 2F & 2C-1 compatibility issue and see how others deal with this. But I think the CNVcalc website probably wants user to consider 2F similar to BA1 and use it to override 2C-1 and others.

AF cutoff would be helpful and keeping the value in the final output probably will be also helpful to classify variants in AD or AR genes. 

Thanks!

**Comment by lgmgeo** [comment]
> I'll ask the 2F & 2C-1 compatibility issue and see how others deal with this
Great! Any feedback will be welcome in this github.

**Comment by Bin-Guan** [comment]
I discussed this with others who are more familiar with CNV, and we agree that 2F can act like BA1 if AF>5% (DGV gold, gnomAD etc). For an AD condition, it is safe to classify it as benign if > 1%; if AR, then may be safer to classify it as VUS when AF is ~ 1% and no other information. Thus, 2F here can precede 2C-1 in the example above.

Clingen CNVcalc is certainly hard to automate, because SV may have partial overlap. Franklin also attempts to automate this process.  In this example, franklin applied 2F and 4O, and final classification is benign. https://franklin.genoox.com/clinical-db/variant/sv/chr1-108733325-108737251-DEL?app=acmg-classification-sv. In my opinion, 4O is probably more appropriate than 2F in this instance. 2F refers to other situations where a deletion in a region is known to be benign, but AF in general population is < 1%.

**Comment by lgmgeo** [comment]
Thanks a lot for your feedback.
I have asked colleagues to also participate in this discussion to share our points of view.

**Comment by jbmtp** [comment]
The ACMG classification only retains genes with an HI score of 3 defined by Clingen (https://dosage.clinicalgenome.org/).
We have chosen to extend the criteria to all OMIM genes, which explains your result:
- for your example, if we strictly followed the ACMG recommendations, the 2C-1 criterion is not retained because SLC25A24 does not have a Clingen score, on the other hand we could use 2F
- with v 3.0.5, SLC25A24 is an OMIM gene so the 2C-1 criterion is applied (2F cannot be used because the section is exclusive)

**Comment by lgmgeo** [comment]
November 8, 2021: v3.1 is posted

>I will add a -benignAF option, set by default to 1% and with a range values from 0.1% to 10%.
So that each user can defined the AF cutoff for benign SV on their own.

Done!

**-benignAF**:   Allele frequency threshold to select the benign SV in the data sources
Range values: [0.001-0.1], default = 0.01 (i.e. 1%)

>Add column for frequencies in databases for B_* infos

Done!

In v3.1, you now have access to additional output columns:
B_gain_AFmax: Maximum allele frequency of the reported benign gain genomic regions (if available)
B_loss_AFmax:  Maximum allele frequency of the reported benign loss genomic regions (if available)
B_ins_AFmax: Maximum allele frequency of the reported benign insertion genomic regions (if available)
B_inv_AFmax: Maximum allele frequency of the reported benign inversion genomic regions (if available)
