### ISSUE TITLE
Seeking clarity on the Annotation code/Method

### ISSUE THREAD

**Issue by Mkddb** [lgmgeo/AnnotSV#41]
Hello Veronique,

Hope you are doing great out there.

I have a strange observation for a variant. 
Coordinates : 1_108190708_108194629_DEL_1
Length : -3921bp
It's a Homozygous deletion in my VCF, covering 1st exon of 2nd transcript isoform for the gene SLC25A24 gene. As per the ACMG annotation via AnnotSV, it gets a criteria of 1A;2C-1 (SLC25A24);3A (1 gene);5F and a Likely pathogenic classification (Full = 4)

But, the similar deletion have been reported as Benign:

Source : 1000g;DDD:2369;IMH;dgv59e199;esv3587125;gnomAD-SV_v2.1_DEL_1_6945 
Coordinates : 1:108189691-108195753;1:108190666-108194615;1:108190666-108194615;1:108190702-108194629;1:108190703-108194629;1:108190703-108194646

So, i am having doubt that it should be assigned 2F under Section 2 and a clear benign classification at the end.

Will you please look into this and update accordingly.

Thanks in Advance.

**Comment by lgmgeo** [comment]
Hi Mkddb ,

I have run your example (1:108190708-108194629 DEL) on the web server. Here are the results:
https://lbgi.fr/AnnotSV/display?id=5yHlaoP798
The DEL (3921 bp) overlaps with the VAV3 gene (intron2-intron2).
It does not match your results.
What options did you use ? 
Please, reproduce your run on the webserver (https://lbgi.fr/AnnotSV/runjob) and send me the job id.

Best,
Véronique

**Comment by Mkddb** [comment]
Ohh sorry, 

i forgot to mention. it was -genomeBuild GRCh38

**Comment by Mkddb** [comment]
https://lbgi.fr/AnnotSV/display?id=ChVWaEzlcs

**Comment by lgmgeo** [comment]
Ok, got it.

Thanks for your comment, I need to clarify in the README the annotation method used in AnnotSV:
In each section, only 1 criterion (from the most pathogenic to the least) is assigned.  
In your example, criterion 2F is not assigned because criterion 2C-1 is more pathogenic.

Indeed, the SLC25A24 gene is an OMIM morbid gene. The molecular basis of the Fontaine progeroid syndrome is known; mutations has been found in the gene (see the "Molecular Genetics" section at https://www.omim.org/entry/608744).

Regarding your DEL, the 2C-1 criteria is verified (the coding sequence of the morbid gene is involved).
This explains the ACMG_class class of 4.

Hope that it's clearer.

**Comment by Mkddb** [comment]
Thanks for the insights. 

Yes, i agree with the comments.

now, i am having major doubt whether i should consider the variant as likley pathogenic as per 2C-1 or the benign as per 2F ? 
also, the same variant has high allele frequency in healthy individuals. see gnomAD screenshot below. 
![gnomad_pic01](https://user-images.githubusercontent.com/61584787/109498024-e6d19c80-7ab8-11eb-8131-da7548967f7c.png)
Similarly in 1000 genome data. moreover, it could have been assigned 4O as per the Section 4 in ACMG guidelines (not imlemented in AnnotSV).

what's your view, particularly for this variant in a healthy individual vs in an individual with progeria like symptoms ?

**Comment by lgmgeo** [comment]
In my opinion, this DEL requires close consultation of the clinical context (patient phenotype).
Does the patient have symptoms similar to those of progeria?
If so, this DEL can be considered pathogenic. Functional experiments must be carried out.
Otherwise, this DEL does not appear to be responsible for the disease of your patient.

This gene has several transcripts isoform. This may explain why some variants are pathogenic while others are not. Experts need to assess the impact or not of your DEL.

**Comment by Mkddb** [comment]
Great,

Thanks for the suggestion. Yes, the patient appear to have such symptoms.
Will look for some functional experiments for the same, keeping in mind for multiple transcript isoforms.

Thanks for the clarification and valueable insights.

**Comment by Mkddb** [comment]
Hi Veronique,

Sorry for disturbing again.
I had another query related with the same case, so opted to extend the same thread. 

$ANNOTSV/bin/AnnotSV -SVinputfile sample1_diploidSV.vcf -SVinputInfo 1 -outputFile sample1_diploidSV_annotatewithRE.tsv -genomeBuild GRCh38 -REreport yes

These are the entries in "REgene" column -  VAV3; NBPF4; SLC25A24 (morbid); in "full line" for the variant:1_108190708_108194629_DEL_1
I wanted to check the source and coordinates for the regulatory elements associated with these genes. 

But, i dnt see any “*.SV_RE_intersect.tmp” output file.

I checked for the files in AnnotSV-3.0.5/share/AnnotSV/Annotations_Human/FtIncludedInSV/RegulatoryElements/GRCh38 folder.
these files are there : EA_ENSEMBL_GRCh38.sorted.bed  EA_RefSeq_GRCh38.sorted.bed  promoter_500bp_ENSEMBL_GRCh38.sorted.bed  promoter_500bp_RefSeq_GRCh38.sorted.bed

It seems that i need to download EnhancerAtlas dataset. 

can you please check if i am missing something else also ?

**Comment by lgmgeo** [comment]
Thanks for the report, it was a stupid glitch...
It is fixed in v3.0.6.
Otherwise, you can still run 3.0.5 if you rename the outputfile from: 
-outputFile sample1_diploidSV_annotatewithRE.tsv
at 
-outputFile sample1_diploidSV_annotatewithRE.annotated.tsv

**Comment by Mkddb** [comment]
Great. 

Thanks a lot for the quick resolution. 
That's okay to have glitches too, sometimes. :P 
“Every problem is a gift — without problems we would not grow.” – Anthony Robbins
Good luck for the future endeavours.

With Kind regards..
