### ISSUE TITLE
Annotating MEIs, not seeing AnnotSV ranking

### ISSUE THREAD

**Issue by Phillip-a-richmond** [lgmgeo/AnnotSV#50]
Hello,

I'm annotating a merged output from MELT, and I'm getting full annotations but not seeing any AnnotSV ranking scores or criteria. 

I'm using the latest AnnotSV (3.0.7).

Thanks!
Phil

**Comment by lgmgeo** [comment]
Hi Philip,

Can you run an example on the web server ([https://lbgi.fr/AnnotSV/runjob](https://lbgi.fr/AnnotSV/runjob)) and tell me the job ID?
So I could have a look on it.

Best regards,
Véronique

**Comment by lgmgeo** [comment]
In order to be able to rank the SV, AnnotSV requires that the type of SV is provided (duplication, deletion...) in the input SV file (BED or VCF). Is it the case in your input file?

**Comment by Phillip-a-richmond** [comment]
Here's the job id:

nqF1lKaYvR

Here's the input VCF and the output I get from my local install.

[MergedMEI_vcf.txt](https://github.com/lgmgeo/AnnotSV/files/6572756/MergedMEI_vcf.txt)
[MergedMEI_annotated_tsv.txt](https://github.com/lgmgeo/AnnotSV/files/6572758/MergedMEI_annotated_tsv.txt)

**Comment by lgmgeo** [comment]
First, your job on the web server ([https://lbgi.fr/AnnotSV/downloadretrievetsv?id=nqF1lKaYvR](https://lbgi.fr/AnnotSV/downloadretrievetsv?id=nqF1lKaYvR)) failed because you don't use the good option value for "-SVinputFile".
Extension file should be ".bed" or ".vcf"
Please, rename MergedMEI_vcf.txt to MergedMEI_vcf.vcf

Regarding the AnnotSV ranking (v3), the score is an adaptation of the work provided by the joint consensus recommendation of ACMG and ClinGen ([Riggs et al., 2020](https://www.nature.com/articles/s41436-019-0686-8)). It only works for copy-number losses and copy-number gains. 
Unfortunately, your input file only contains insertions, not yet scored in AnnotSV.
