### ISSUE TITLE
ACMG 2019 Criteria 

### ISSUE THREAD

**Issue by rvaldes** [lgmgeo/AnnotSV#6]
Have you planned to update your SV ranking according to the 2019 ACMG Criteria?
Thanks!

**Comment by lgmgeo** [comment]
Yes, for sure, that makes sense for me!
Thank you for your suggestion (and thanks to the other users who also contacted me about that).
But this will still take some time because new features to investigate are piling up...
I apologize for the inconvenience of this delay,

Best regards,
Véronique

[Technical standards for the interpretation and reporting of constitutional copy-number variants: a joint consensus recommendation of the American College of Medical Genetics and Genomics (ACMG) and the Clinical Genome Resource (ClinGen)](https://www.nature.com/articles/s41436-019-0686-8)

**Comment by lgmgeo** [comment]
Any idea for implementing the ACMG section 4 ?

I mean...
How to determine if the reported phenotype of a CNV loss (for example from ClinVar: https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh37/clinvar_20201031.vcf.gz) is:
- highly specific and relatively unique to the gene
- consistent with the gene, highly specific but NOT unique to the gene
- consistent with the gene, NOT highly specific and/or WITH high genetic heterogeneity
- NOT consistent with what is expected for the gene

Thank you for any help you could provide me.

**Comment by lgmgeo** [comment]
AnnotSV 3.0 is alive!
The updated ACMG guidelines for SV ranking (Riggs et al 2020) have been implemented.

The comprehensive and detailed scoring guidelines are available in the [Scoring_Criteria_AnnotSV_latest.xlsx](https://www.lbgi.fr/AnnotSV/Documentation/Scoring_Criteria_AnnotSV_latest.xlsx) file (see Table1 for loss SV and Table2 for gain SV).

Happy exploring ;o)
