### ISSUE TITLE
DGV are no longer in the result

### ISSUE THREAD

**Issue by xiucz** [lgmgeo/AnnotSV#62]
Hi,
In the AnnotSV version 3.3, the DGV annotations are not in the result, how can I reobtain it ?
![image](https://user-images.githubusercontent.com/12706146/138237320-fc361f9b-0938-4fde-9daf-b3e18fa8421d.png)

Thank you.
Xiucz

**Comment by xiucz** [comment]
I am eager to test the new v3.1 version, because  the DGV AF is important to filter CNVs.😊.

**Comment by lgmgeo** [comment]
v3.1 is planned around November 15th,
Sorry for the delay

**Comment by lgmgeo** [comment]
v3.1 is posted!

Does this meet your needs?
Thank you for any feedback you can provide me on benign AF.

**Comment by xiucz** [comment]
Thank you, I will feedback later.

**Comment by JMdeSteAgathe** [comment]
Hello,
would it be possible to add the `DGV Gold Standard frequencies` to the annotation?

Indeed, the [README](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf), mentions DGV Gold Standard:
> DGV Gold Standard (The “B_*_source” output values begin with “dgv”, “nsv” or “esv”)

But, I think the DGV Gold Standard values begin with "gssv". My personnal suggestion would be to provide it separately, in a dedicated and unique DGV column where the frequency displayed corresponds to the same `CNV type` (i.e. gain / loss). And set to `0` when empty.

It would be so helpful as it would be the safest and quickest way to filter frequent CNVs, which I find quite hard to do in the current config.
Best,
Jean-Madeleine

**Comment by lgmgeo** [comment]
Hi Jean-Madeleine,

Different sources of benign genes or genomic regions have been merged in AnnotSV to create the BENIGN dataset.

First, my apologies, it's not the "DGV Gold Standard" (as mentioned below in the README) but the "DGV Variants" that is used in AnnotSV.

![image](https://user-images.githubusercontent.com/49909073/221146734-38cd109d-db7d-428c-91a5-c576b39e334e.png)

Indeed, in the README, the "DGV benign SV annotations" section indicates the good sources:

![image](https://user-images.githubusercontent.com/49909073/221152517-93e71af2-e0e1-464e-8680-e7a7810ae2cb.png)

The idea in AnnotSV is to not increase the output columns. That's why, for benign annotation, you don't have a separate output column dedicated to DGV.

Frequencies are available for filtering with the `B_gain_AFmax`, `B_loss_AFmax`... features.

![image](https://user-images.githubusercontent.com/49909073/221147991-e58ff710-1500-4166-9d15-40abcf6cde91.png)

You can change the default Allele frequency threshold (1%) with the “-benignAF” option:

![image](https://user-images.githubusercontent.com/49909073/221153868-4fb991f4-a900-48da-8519-7637151e7806.png)

Best,

Véronique
PS: The README will be updated with the next version.

**Comment by JMdeSteAgathe** [comment]
Thank you Véronique for your quick and kind response.
Here are the two difficulties I have with your solution:

- it's time consuming to handle two different AF columns that need to be successively filtered with their matched SV-TYPE
- DGV Gold is curated. For example, if I enter a pathogenic deletion of _MYCN_ (hg19_`chr2:16080337-16087409 DEL`) in AnnotSV, it will wrongly classify it as `ACMG_class=3` due to the errors contained in DGV bulk (`B_loss_AFmax=0.0100`;`B_loss_source=dgv1102e212`). I think this is the reason why UCSC removed this track from their hg19 clinical CNV recommended track set.

I can imagine why adding new columns can be tricky! I am sorry if I seem insisting... I genuinely know quite a bunch of AnnotSV users who would love to have a filterable and unique DGV gold frequency. 😀
Best,
Jean-Madeleine

**Comment by lgmgeo** [comment]
The best solution would be to select benign SV more stricly.
Why not to run AnnotSV with the following option: `-benignAF 0.005` (Allele frequency threshold to select the benign SV in the data sources)
