### ISSUE TITLE
False positive deletion SNV/indel vcf

### ISSUE THREAD

**Issue by ashamehta** [lgmgeo/AnnotSV#64]
Hello,

Thank you for all your work on AnnotSV, it's been so helpful for us. 

I have a question regarding the exact specifications required for the jointly called cohort VCF used for false positive deletion filtering. We are planning how to process a large amount of jointly-called data and would like to have a clear goal in mind before diving in. That being said, would a jointly called vcf that contains ~3000 samples and a FORMAT column that is restricted only to GT work for false positive deletion filtering? Is it preferable to have a vcf with pre-calculated frequencies for each variant? 

Thanks in advance for your clarification,
Asha

**Comment by lgmgeo** [comment]
Hi Asha,

Actually, I never evaluate the "snvIndelFiles" option with so many WGS samples (~3000). 
(I'm in a small lab with currently  less than 50 WGS samples). 
However, recently an AnnotSV user gave me interesting feedback on using around 600 WGS samples and found it to be taking a long time due to the size of their data.

In my opinion, you don't need so many samples for the SV deletion filtration. The use of only ~20/40 controls should be faster. So my advice is to use the "snvIndelSamples" to specify a selection of samples from the VCF. Else, if it's still time consuming, you could directly reduce your SNV/indel VCF to ~20/40 samples (for example with GATK command).

I know it's not a perfect solution...but it can be a middle ground.

In the future (not near), I will refactor AnnotSV in Python then use an SQLite database to store variant data and save time. This problem should be fixed then. But I develop AnnotSV on my free time (analysis for my lab first). So it may take some time...

Otherwise, your idea of ​​restricting the FORMAT column to GT only is really good.
Regarding having a vcf with pre-calculated frequencies for each SNV/indel, AnnotSV cannot process this information for false positive SV deletion.

Best,

Véronique

PS: Just to let you know, a new release of AnnotSV (3.1) is due soon (with updated annotations and new features).

**Comment by ashamehta** [comment]
Hi Véronique, 

Thank you for your insight, this is very helpful. I will test out a smaller control group for false positive SV deletion as you suggested. 

And great to hear that new release is coming soon. I look forward to using it.

Best,
Asha

**Comment by ShrutiMarwaha** [comment]
Thanks Véronique. The next release was indeed very soon! i just got an email! 👌🏽

**Comment by lgmgeo** [comment]
>  I will test out a smaller control group for false positive SV deletion as you suggested.

Please, could you give us your feedback on what worked and what didn't? 
And how long did it take? 
That would be really interesting!!

> Thanks Véronique. The next release was indeed very soon! i just got an email! 👌🏽

;o)

**Comment by ashamehta** [comment]
Will do! It will probably be a couple of weeks, but I'll make sure to follow up here with how it went.
